sudo: required
dist: trusty
group: edge

language: node_js
node_js:
  - '8.10'

before_script:
  - npm install -g @angular/cli
  - npm i npm@latest -g
  - gulp
  - rm -Rf node_modules/electron-builder-squirrel-windows node_modules/electron-windows-notifications #Avoid electron fail

script:
  - cd scripts && ./build_lang.sh && cd ..
  - if [ $TRAVIS_BRANCH == 'MOBILE-2639' ] && [ ! -z $GIT_TOKEN ] ; then git remote set-url origin https://$GIT_TOKEN@github.com/$TRAVIS_REPO_SLUG.git && git fetch -q origin && git add src/assets/lang && git commit -m 'Update lang files [ci skip]' && git push origin $TRAVIS_BRANCH ; fi

after_success:
  - chmod +x scripts/aot.sh
  - scripts/aot.sh
